config/routes.rb
Rails.application.routes.draw do
  resources :journeys
  devise_for :owners
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :consumptions
  resources :owners
  resources :vehicles
  resources :journeys
  
  get '/overview', to: 'overviews#index'
  get '/charging', to: 'charging#show'

  root :controller => 'overviews', :action => 'index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, :format => :json do
    namespace :v1 do
      get  '/chargedata', to: 'chargedata#index'
      post  '/submitdata', to: 'chargedata#submitdata'
      post  '/consumption', to: 'consumption#create'
      post  '/journey', to: 'journey#create'
    end
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :vehicle, optional: true
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :vehicle_id, :email, :id)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_with(model: owner, local: true) do |form| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :owner_name %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.collection_select :vehicle_id, Vehicle.all ,:id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.vehicle %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @owner.vehicle.name %>
  <%= link_to 'Vehicle', vehicle_path(@owner.vehicle) %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>