config/routes.rb
Rails.application.routes.draw do
  resources :journeys
  devise_for :owners
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :consumptions
  resources :owners
  resources :vehicles
  resources :journeys
  
  get '/overview', to: 'overviews#index'
  get '/charging', to: 'charging#show'

  root :controller => 'overviews', :action => 'index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, :format => :json do
    namespace :v1 do
      get  '/chargedata', to: 'chargedata#index'
      post  '/submitdata', to: 'chargedata#submitdata'
      post  '/consumption', to: 'consumption#create'
      post  '/journey', to: 'journey#create'
    end
  end
end

app/models/consumption.rb
class Consumption < ApplicationRecord
  belongs_to :vehicle
  belongs_to :journey
  after_commit { UpdateEnergyJob.perform_later(self) }
end

app/controllers/api/v1/consumption_controller.rb
class API::V1::ConsumptionController < ActionController::API
    
    def create
        @consumption = Consumption.new(consumption_params)
        if @consumption.save
            return render :json => @consumption
        end
        head 400
    end

    def consumption_params
        params.permit(:time, :consumption, :vehicle_id)
    end
end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  before_action :set_consumption, only: [:show, :edit, :update, :destroy]

  # GET /consumptions
  # GET /consumptions.json
  def index
    @consumptions = Consumption.all
  end

  # GET /consumptions/1
  # GET /consumptions/1.json
  def show
  end

  # GET /consumptions/new
  def new
    @consumption = Consumption.new
  end

  # GET /consumptions/1/edit
  def edit
  end

  # POST /consumptions
  # POST /consumptions.json
  def create
    @consumption = Consumption.new(consumption_params)

    respond_to do |format|
      if @consumption.save
        format.html { redirect_to @consumption, notice: 'Consumption was successfully created.' }
        format.json { render :show, status: :created, location: @consumption }
      else
        format.html { render :new }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end 
  end

  # PATCH/PUT /consumptions/1
  # PATCH/PUT /consumptions/1.json
  def update
    respond_to do |format|
      if @consumption.update(consumption_params)
        format.html { redirect_to @consumption, notice: 'Consumption was successfully updated.' }
        format.json { render :show, status: :ok, location: @consumption }
      else
        format.html { render :edit }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumptions/1
  # DELETE /consumptions/1.json
  def destroy
    @consumption.destroy
    respond_to do |format|
      format.html { redirect_to consumptions_url, notice: 'Consumption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumption
      @consumption = Consumption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumption_params
      params.require(:consumption).permit(:time, :consumption, :vehicle_id)
    end
end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper
end

app/views/consumptions/_form.html.erb
<%= form_with(model: consumption, local: true) do |form| %>
  <% if consumption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consumption.errors.count, "error") %> prohibited this consumption from being saved:</h2>

      <ul>
      <% consumption.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time, id: :consumption_time %>
  </div>

  <div class="field">
    <%= form.label :consumption %>
    <%= form.number_field :consumption, id: :consumption_consumption %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.collection_select :vehicle_id, Vehicle.all ,:id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consumptions/edit.html.erb
<h1>Editing Consumption</h1>

<%= render 'form', consumption: @consumption %>

<%= link_to 'Show', @consumption %> |
<%= link_to 'Back', consumptions_path %>

app/views/consumptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consumptions</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Consumption</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consumptions.each do |consumption| %>
      <tr>
        <td><%= consumption.time %></td>
        <td><%= consumption.consumption %></td>
        <td><%= consumption.vehicle %></td>
        <td><%= link_to 'Show', consumption %></td>
        <td><%= link_to 'Edit', edit_consumption_path(consumption) %></td>
        <td><%= link_to 'Destroy', consumption, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consumption', new_consumption_path %>

app/views/consumptions/new.html.erb
<h1>New Consumption</h1>

<%= render 'form', consumption: @consumption %>

<%= link_to 'Back', consumptions_path %>

app/views/consumptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @consumption.time %>
</p>

<p>
  <strong>Consumption:</strong>
  <%= @consumption.consumption %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @consumption.vehicle %>
</p>

<%= link_to 'Edit', edit_consumption_path(@consumption) %> |
<%= link_to 'Back', consumptions_path %>