config/routes.rb
Rails.application.routes.draw do
  resources :journeys
  devise_for :owners
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :consumptions
  resources :owners
  resources :vehicles
  resources :journeys
  
  get '/overview', to: 'overviews#index'
  get '/charging', to: 'charging#show'

  root :controller => 'overviews', :action => 'index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, :format => :json do
    namespace :v1 do
      get  '/chargedata', to: 'chargedata#index'
      post  '/submitdata', to: 'chargedata#submitdata'
      post  '/consumption', to: 'consumption#create'
      post  '/journey', to: 'journey#create'
    end
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :owner
  has_many :consumptions
  has_many :journeys
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :owner_id, :address, :charging_sector, :battery_capacity)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :vehicle_name %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.collection_select :owner_id, Owner.all ,:id, :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :vehicle_address %>
  </div>

  <div class="field">
    <%= form.label :charging_sector %>
    <%= form.text_field :charging_sector, id: :vehicle_charging_sector %>
  </div>

  <div class="field">
    <%= form.label :battery_capacity %>
    <%= form.number_field :battery_capacity, id: :vehicle_battery_capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Address</th>
      <th>Charging sector</th>
      <th>Battery capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.name %></td>
        <td><%= vehicle.owner %></td>
        <td><%= vehicle.address %></td>
        <td><%= vehicle.charging_sector %></td>
        <td><%= vehicle.battery_capacity %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<div class="container">
  <h2> Vehicle Data </h2>
  <p id="notice"><%= notice %></p>
  <div id='map'></div>
<p>
  <strong>Name:</strong>
  <%= @vehicle.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @vehicle.owner.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @vehicle.address %>
</p>

<p>
  <strong>Charging sector:</strong>
  <%= @vehicle.charging_sector %>
</p>

<p>
  <strong>Battery capacity:</strong>
  <%= @vehicle.battery_capacity %>
</p>
<h3>My Recent Journeys</h3>
<table class="table">
  <thead>
    <tr>
      <th>Start</th>
      <th>Destination</th>
      <th>Details</th>
    </tr>
  </thead>
  <tbody>
   <% @vehicle.journeys.each do |journey| %>
    <tr>
      <td scope="row"><%= journey.origin %></td>
      <td scope="row"><%= journey.destination %></td>
      <td scope="row"><%= link_to 'Show', journey %></td>
    </tr>
    <% end%>
  </tbody>
</table>
</div>
<script>
var lat = <%= @vehicle.latitude %>;
var long = <%= @vehicle.longitude %>;
var map = L.map('map').setView([lat, long], 13);
var latlngs =  <%= @vehicle.journeys.map {|jny| jny.consumptions.map {|cns| [cns.lat.to_f.round(3), cns.lon.to_f.round(3)]}} %>
var polyline = L.polyline(latlngs, {color: 'red'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([lat, long]).addTo(map)
    .bindPopup('<%= @vehicle.name %>')
    .openPopup();

</script>
<%= link_to 'Add Journey', new_journey_path(@vehicle) %>
<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>