config/routes.rb
Rails.application.routes.draw do
  resources :journeys
  devise_for :owners
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :consumptions
  resources :owners
  resources :vehicles
  resources :journeys
  
  get '/overview', to: 'overviews#index'
  get '/charging', to: 'charging#show'

  root :controller => 'overviews', :action => 'index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, :format => :json do
    namespace :v1 do
      get  '/chargedata', to: 'chargedata#index'
      post  '/submitdata', to: 'chargedata#submitdata'
      post  '/consumption', to: 'consumption#create'
      post  '/journey', to: 'journey#create'
    end
  end
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :owner
  belongs_to :vehicle
  has_many :consumptions
  accepts_nested_attributes_for :consumptions, allow_destroy: true

  def start_time
    consumptions.first.time
  end
  
  def end_time
    consumptions.last.time
  end
end

app/controllers/api/v1/journey_controller.rb
class API::V1::JourneyController < ActionController::API
    
    def create
        vehicle = Vehicle.find(journey_params[:vehicle_id])
        param_hash = params.to_unsafe_h.to_h

        @journey = Journey.new(journey_params)
        cons_arr = []
        consumptions =   param_hash['consumptions'].each do |x|
             consumption = Consumption.new(x)
             consumption.journey = @journey
             consumption.vehicle = vehicle
             consumption.save
             cons_arr.push(consumption)
             
        end
        @journey.consumptions = cons_arr
        @journey.owner = vehicle.owner
        if @journey.save
            return render :json => @journey
        end
        head 400
    end

    def journey_params
        params.require(:journey).permit(:time, :vehicle_id, {consumptions: :lat}, :origin, :destination, :originLat, :originLon, :destinationLat, :destinationLon)

    end

end

app/controllers/journeys_controller.rb
class JourneysController < InheritedResources::Base

  def new
    @journey = Journey.new
  end


  private

    def journey_params
      params.require(:journey).permit(:owner_id, :vehicle_id, :origin, :destination)
    end
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/journeys/_form.html.erb
<%= form_with(model: journey, local: true) do |form| %>
  <% if journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journey.errors.count, "error") %> prohibited this journey from being saved:</h2>

      <ul>
      <% journey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id, id: :journey_owner_id %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.collection_select :vehicle_id, Vehicle.all ,:id, :name %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :journey_origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :journey_destination %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journeys/edit.html.erb
<h1>Editing Journey</h1>

<%= render 'form', journey: @journey %>

<%= link_to 'Show', @journey %> |
<%= link_to 'Back', journeys_path %>

app/views/journeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journeys</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Vehicle</th>
      <th>Origin</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journeys.each do |journey| %>
      <tr>
        <td><%= journey.owner %></td>
        <td><%= journey.vehicle %></td>
        <td><%= journey.origin %></td>
        <td><%= journey.destination %></td>
        <td><%= link_to 'Show', journey %></td>
        <td><%= link_to 'Edit', edit_journey_path(journey) %></td>
        <td><%= link_to 'Destroy', journey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journey', new_journey_path %>

app/views/journeys/new.html.erb
<h1>New Journey</h1>

<%= render 'form', journey: @journey %>

<%= link_to 'Back', journeys_path %>

app/views/journeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @journey.owner %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @journey.vehicle %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @journey.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @journey.destination %>
</p>

<%= link_to 'Edit', edit_journey_path(@journey) %> |
<%= link_to 'Back', journeys_path %>